/* tslint:disable */
/* eslint-disable */
/**
 * Swagger API (api)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20260216
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, BaseAPI, operationServerMap } from './base';
export const ProductCurrencyEnum = {
    Rub: 'RUB',
    Usd: 'USD',
    Eur: 'EUR',
    Xtr: 'XTR'
};
export const ProductCreateRequestCurrencyEnum = {
    Rub: 'RUB',
    Usd: 'USD',
    Eur: 'EUR',
    Xtr: 'XTR'
};
export const ProductListResponseProductsInnerCurrencyEnum = {
    Rub: 'RUB',
    Usd: 'USD',
    Eur: 'EUR',
    Xtr: 'XTR'
};
export const ProductUpdateRequestCurrencyEnum = {
    Rub: 'RUB',
    Usd: 'USD',
    Eur: 'EUR',
    Xtr: 'XTR'
};
export const StatisticsGetResponseRecordsInnerTypeEnum = {
    Messages: 'MESSAGES',
    Chats: 'CHATS',
    Payments: 'PAYMENTS'
};
export const TransactionsListResponseTransactionsInnerTypeEnum = {
    Deposit: 'DEPOSIT',
    Payment: 'PAYMENT'
};
/**
 * ControllerApi - axios parameter creator
 */
export const ControllerApiAxiosParamCreator = function (configuration) {
    return {
        /**
         *
         * @summary Activate telegram bot
         * @param {string} botId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerBotActivate: async (botId, options = {}) => {
            // verify required parameter 'botId' is not null or undefined
            assertParamExists('controllerBotActivate', 'botId', botId);
            const localVarPath = `/api/v1/bots/{bot_id}/activate`
                .replace(`{${"bot_id"}}`, encodeURIComponent(String(botId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Register telegram bot on platform
         * @param {BotCreateRequest} botCreateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerBotCreate: async (botCreateRequest, options = {}) => {
            // verify required parameter 'botCreateRequest' is not null or undefined
            assertParamExists('controllerBotCreate', 'botCreateRequest', botCreateRequest);
            const localVarPath = `/api/v1/bots`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            localVarRequestOptions.data = serializeDataIfNeeded(botCreateRequest, localVarRequestOptions, configuration);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Deactivate telegram bot
         * @param {string} botId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerBotDeactivate: async (botId, options = {}) => {
            // verify required parameter 'botId' is not null or undefined
            assertParamExists('controllerBotDeactivate', 'botId', botId);
            const localVarPath = `/api/v1/bots/{bot_id}/deactivate`
                .replace(`{${"bot_id"}}`, encodeURIComponent(String(botId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Delete telegram bot from platform
         * @param {string} botId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerBotDelete: async (botId, options = {}) => {
            // verify required parameter 'botId' is not null or undefined
            assertParamExists('controllerBotDelete', 'botId', botId);
            const localVarPath = `/api/v1/bots/{bot_id}`
                .replace(`{${"bot_id"}}`, encodeURIComponent(String(botId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Get telegram bot on platform
         * @param {string} botId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerBotGet: async (botId, options = {}) => {
            // verify required parameter 'botId' is not null or undefined
            assertParamExists('controllerBotGet', 'botId', botId);
            const localVarPath = `/api/v1/bots/{bot_id}`
                .replace(`{${"bot_id"}}`, encodeURIComponent(String(botId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            localVarHeaderParameter['Accept'] = 'application/json';
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary List all telegram bots on platform
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerBotList: async (options = {}) => {
            const localVarPath = `/api/v1/bots`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            localVarHeaderParameter['Accept'] = 'application/json';
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Update telegram bot on platform
         * @param {string} botId
         * @param {BotUpdateRequest} botUpdateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerBotUpdate: async (botId, botUpdateRequest, options = {}) => {
            // verify required parameter 'botId' is not null or undefined
            assertParamExists('controllerBotUpdate', 'botId', botId);
            // verify required parameter 'botUpdateRequest' is not null or undefined
            assertParamExists('controllerBotUpdate', 'botUpdateRequest', botUpdateRequest);
            const localVarPath = `/api/v1/bots/{bot_id}`
                .replace(`{${"bot_id"}}`, encodeURIComponent(String(botId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            localVarRequestOptions.data = serializeDataIfNeeded(botUpdateRequest, localVarRequestOptions, configuration);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Create product for telegram bot
         * @param {ProductCreateRequest} productCreateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerProductCreate: async (productCreateRequest, options = {}) => {
            // verify required parameter 'productCreateRequest' is not null or undefined
            assertParamExists('controllerProductCreate', 'productCreateRequest', productCreateRequest);
            const localVarPath = `/api/v1/products`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            localVarRequestOptions.data = serializeDataIfNeeded(productCreateRequest, localVarRequestOptions, configuration);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Delete product for telegram bot
         * @param {string} productId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerProductDelete: async (productId, options = {}) => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('controllerProductDelete', 'productId', productId);
            const localVarPath = `/api/v1/products/{product_id}`
                .replace(`{${"product_id"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Get product for telegram bot
         * @param {string} productId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerProductGet: async (productId, options = {}) => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('controllerProductGet', 'productId', productId);
            const localVarPath = `/api/v1/products/{product_id}`
                .replace(`{${"product_id"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            localVarHeaderParameter['Accept'] = 'application/json';
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary List all products for telegram bot
         * @param {string} botId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerProductList: async (botId, options = {}) => {
            // verify required parameter 'botId' is not null or undefined
            assertParamExists('controllerProductList', 'botId', botId);
            const localVarPath = `/api/v1/products`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            if (botId !== undefined) {
                localVarQueryParameter['bot_id'] = botId;
            }
            localVarHeaderParameter['Accept'] = 'application/json';
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Update product for telegram bot
         * @param {string} productId
         * @param {ProductUpdateRequest} productUpdateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerProductUpdate: async (productId, productUpdateRequest, options = {}) => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('controllerProductUpdate', 'productId', productId);
            // verify required parameter 'productUpdateRequest' is not null or undefined
            assertParamExists('controllerProductUpdate', 'productUpdateRequest', productUpdateRequest);
            const localVarPath = `/api/v1/products/{product_id}`
                .replace(`{${"product_id"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            localVarRequestOptions.data = serializeDataIfNeeded(productUpdateRequest, localVarRequestOptions, configuration);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary List of promt presets for telegram bot
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerPromptPresetList: async (options = {}) => {
            const localVarPath = `/api/v1/settings/prompt-presets`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            localVarHeaderParameter['Accept'] = 'application/json';
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Get statistics for user
         * @param {string} botId
         * @param {string} startTime
         * @param {string} endTime
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerStatisticsGet: async (botId, startTime, endTime, options = {}) => {
            // verify required parameter 'botId' is not null or undefined
            assertParamExists('controllerStatisticsGet', 'botId', botId);
            // verify required parameter 'startTime' is not null or undefined
            assertParamExists('controllerStatisticsGet', 'startTime', startTime);
            // verify required parameter 'endTime' is not null or undefined
            assertParamExists('controllerStatisticsGet', 'endTime', endTime);
            const localVarPath = `/api/v1/statistics`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            if (botId !== undefined) {
                localVarQueryParameter['bot_id'] = botId;
            }
            if (startTime !== undefined) {
                localVarQueryParameter['start_time'] = startTime;
            }
            if (endTime !== undefined) {
                localVarQueryParameter['end_time'] = endTime;
            }
            localVarHeaderParameter['Accept'] = 'application/json';
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Deposit transaction
         * @param {TransactionBillRequest} transactionBillRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerTransactionBill: async (transactionBillRequest, options = {}) => {
            // verify required parameter 'transactionBillRequest' is not null or undefined
            assertParamExists('controllerTransactionBill', 'transactionBillRequest', transactionBillRequest);
            const localVarPath = `/api/v1/transactions/bill`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            localVarHeaderParameter['Content-Type'] = 'application/json';
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            localVarRequestOptions.data = serializeDataIfNeeded(transactionBillRequest, localVarRequestOptions, configuration);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Get transactions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerTransactionsList: async (options = {}) => {
            const localVarPath = `/api/v1/transactions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            localVarHeaderParameter['Accept'] = 'application/json';
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    };
};
/**
 * ControllerApi - functional programming interface
 */
export const ControllerApiFp = function (configuration) {
    const localVarAxiosParamCreator = ControllerApiAxiosParamCreator(configuration);
    return {
        /**
         *
         * @summary Activate telegram bot
         * @param {string} botId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controllerBotActivate(botId, options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controllerBotActivate(botId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControllerApi.controllerBotActivate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Register telegram bot on platform
         * @param {BotCreateRequest} botCreateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controllerBotCreate(botCreateRequest, options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controllerBotCreate(botCreateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControllerApi.controllerBotCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Deactivate telegram bot
         * @param {string} botId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controllerBotDeactivate(botId, options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controllerBotDeactivate(botId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControllerApi.controllerBotDeactivate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Delete telegram bot from platform
         * @param {string} botId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controllerBotDelete(botId, options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controllerBotDelete(botId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControllerApi.controllerBotDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Get telegram bot on platform
         * @param {string} botId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controllerBotGet(botId, options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controllerBotGet(botId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControllerApi.controllerBotGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary List all telegram bots on platform
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controllerBotList(options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controllerBotList(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControllerApi.controllerBotList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Update telegram bot on platform
         * @param {string} botId
         * @param {BotUpdateRequest} botUpdateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controllerBotUpdate(botId, botUpdateRequest, options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controllerBotUpdate(botId, botUpdateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControllerApi.controllerBotUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Create product for telegram bot
         * @param {ProductCreateRequest} productCreateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controllerProductCreate(productCreateRequest, options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controllerProductCreate(productCreateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControllerApi.controllerProductCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Delete product for telegram bot
         * @param {string} productId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controllerProductDelete(productId, options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controllerProductDelete(productId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControllerApi.controllerProductDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Get product for telegram bot
         * @param {string} productId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controllerProductGet(productId, options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controllerProductGet(productId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControllerApi.controllerProductGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary List all products for telegram bot
         * @param {string} botId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controllerProductList(botId, options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controllerProductList(botId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControllerApi.controllerProductList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Update product for telegram bot
         * @param {string} productId
         * @param {ProductUpdateRequest} productUpdateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controllerProductUpdate(productId, productUpdateRequest, options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controllerProductUpdate(productId, productUpdateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControllerApi.controllerProductUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary List of promt presets for telegram bot
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controllerPromptPresetList(options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controllerPromptPresetList(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControllerApi.controllerPromptPresetList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Get statistics for user
         * @param {string} botId
         * @param {string} startTime
         * @param {string} endTime
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controllerStatisticsGet(botId, startTime, endTime, options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controllerStatisticsGet(botId, startTime, endTime, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControllerApi.controllerStatisticsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Deposit transaction
         * @param {TransactionBillRequest} transactionBillRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controllerTransactionBill(transactionBillRequest, options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controllerTransactionBill(transactionBillRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControllerApi.controllerTransactionBill']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Get transactions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controllerTransactionsList(options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controllerTransactionsList(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControllerApi.controllerTransactionsList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    };
};
/**
 * ControllerApi - factory interface
 */
export const ControllerApiFactory = function (configuration, basePath, axios) {
    const localVarFp = ControllerApiFp(configuration);
    return {
        /**
         *
         * @summary Activate telegram bot
         * @param {string} botId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerBotActivate(botId, options) {
            return localVarFp.controllerBotActivate(botId, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Register telegram bot on platform
         * @param {BotCreateRequest} botCreateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerBotCreate(botCreateRequest, options) {
            return localVarFp.controllerBotCreate(botCreateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Deactivate telegram bot
         * @param {string} botId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerBotDeactivate(botId, options) {
            return localVarFp.controllerBotDeactivate(botId, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Delete telegram bot from platform
         * @param {string} botId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerBotDelete(botId, options) {
            return localVarFp.controllerBotDelete(botId, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Get telegram bot on platform
         * @param {string} botId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerBotGet(botId, options) {
            return localVarFp.controllerBotGet(botId, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary List all telegram bots on platform
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerBotList(options) {
            return localVarFp.controllerBotList(options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Update telegram bot on platform
         * @param {string} botId
         * @param {BotUpdateRequest} botUpdateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerBotUpdate(botId, botUpdateRequest, options) {
            return localVarFp.controllerBotUpdate(botId, botUpdateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Create product for telegram bot
         * @param {ProductCreateRequest} productCreateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerProductCreate(productCreateRequest, options) {
            return localVarFp.controllerProductCreate(productCreateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Delete product for telegram bot
         * @param {string} productId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerProductDelete(productId, options) {
            return localVarFp.controllerProductDelete(productId, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Get product for telegram bot
         * @param {string} productId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerProductGet(productId, options) {
            return localVarFp.controllerProductGet(productId, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary List all products for telegram bot
         * @param {string} botId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerProductList(botId, options) {
            return localVarFp.controllerProductList(botId, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Update product for telegram bot
         * @param {string} productId
         * @param {ProductUpdateRequest} productUpdateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerProductUpdate(productId, productUpdateRequest, options) {
            return localVarFp.controllerProductUpdate(productId, productUpdateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary List of promt presets for telegram bot
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerPromptPresetList(options) {
            return localVarFp.controllerPromptPresetList(options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Get statistics for user
         * @param {string} botId
         * @param {string} startTime
         * @param {string} endTime
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerStatisticsGet(botId, startTime, endTime, options) {
            return localVarFp.controllerStatisticsGet(botId, startTime, endTime, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Deposit transaction
         * @param {TransactionBillRequest} transactionBillRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerTransactionBill(transactionBillRequest, options) {
            return localVarFp.controllerTransactionBill(transactionBillRequest, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Get transactions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerTransactionsList(options) {
            return localVarFp.controllerTransactionsList(options).then((request) => request(axios, basePath));
        },
    };
};
/**
 * ControllerApi - object-oriented interface
 */
export class ControllerApi extends BaseAPI {
    /**
     *
     * @summary Activate telegram bot
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotActivate(botId, options) {
        return ControllerApiFp(this.configuration).controllerBotActivate(botId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary Register telegram bot on platform
     * @param {BotCreateRequest} botCreateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotCreate(botCreateRequest, options) {
        return ControllerApiFp(this.configuration).controllerBotCreate(botCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary Deactivate telegram bot
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotDeactivate(botId, options) {
        return ControllerApiFp(this.configuration).controllerBotDeactivate(botId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary Delete telegram bot from platform
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotDelete(botId, options) {
        return ControllerApiFp(this.configuration).controllerBotDelete(botId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary Get telegram bot on platform
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotGet(botId, options) {
        return ControllerApiFp(this.configuration).controllerBotGet(botId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary List all telegram bots on platform
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotList(options) {
        return ControllerApiFp(this.configuration).controllerBotList(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary Update telegram bot on platform
     * @param {string} botId
     * @param {BotUpdateRequest} botUpdateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotUpdate(botId, botUpdateRequest, options) {
        return ControllerApiFp(this.configuration).controllerBotUpdate(botId, botUpdateRequest, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary Create product for telegram bot
     * @param {ProductCreateRequest} productCreateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductCreate(productCreateRequest, options) {
        return ControllerApiFp(this.configuration).controllerProductCreate(productCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary Delete product for telegram bot
     * @param {string} productId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductDelete(productId, options) {
        return ControllerApiFp(this.configuration).controllerProductDelete(productId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary Get product for telegram bot
     * @param {string} productId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductGet(productId, options) {
        return ControllerApiFp(this.configuration).controllerProductGet(productId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary List all products for telegram bot
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductList(botId, options) {
        return ControllerApiFp(this.configuration).controllerProductList(botId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary Update product for telegram bot
     * @param {string} productId
     * @param {ProductUpdateRequest} productUpdateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductUpdate(productId, productUpdateRequest, options) {
        return ControllerApiFp(this.configuration).controllerProductUpdate(productId, productUpdateRequest, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary List of promt presets for telegram bot
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerPromptPresetList(options) {
        return ControllerApiFp(this.configuration).controllerPromptPresetList(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary Get statistics for user
     * @param {string} botId
     * @param {string} startTime
     * @param {string} endTime
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerStatisticsGet(botId, startTime, endTime, options) {
        return ControllerApiFp(this.configuration).controllerStatisticsGet(botId, startTime, endTime, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary Deposit transaction
     * @param {TransactionBillRequest} transactionBillRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerTransactionBill(transactionBillRequest, options) {
        return ControllerApiFp(this.configuration).controllerTransactionBill(transactionBillRequest, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary Get transactions
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerTransactionsList(options) {
        return ControllerApiFp(this.configuration).controllerTransactionsList(options).then((request) => request(this.axios, this.basePath));
    }
}
