/**
 * Swagger API (api)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20260216
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import type { RequestArgs } from './base';
import { BaseAPI } from './base';
export interface Bot {
    'active': boolean;
    'botId': string;
    'presetId': string;
    'prompt': string;
    'token': string;
}
export interface BotCreateRequest {
    'botToken': string;
}
export interface BotListResponseBotsInner {
    'active': boolean;
    'botId': string;
    'presetId': string;
    'prompt': string;
    'token': string;
}
export interface BotUpdateRequest {
    'presetId': string;
    'prompt': string;
}
export interface Product {
    'botId': string;
    'currency': ProductCurrencyEnum;
    'description': string;
    'imageUrl': string;
    'name': string;
    'payLink': string;
    'price': string;
    'productId': string;
    'useInvoice': boolean;
}
export declare const ProductCurrencyEnum: {
    readonly Rub: "RUB";
    readonly Usd: "USD";
    readonly Eur: "EUR";
    readonly Xtr: "XTR";
};
export type ProductCurrencyEnum = typeof ProductCurrencyEnum[keyof typeof ProductCurrencyEnum];
export interface ProductCreateRequest {
    'botId': string;
    'currency': ProductCreateRequestCurrencyEnum;
    'description': string;
    'imageUrl': string;
    'name': string;
    'payLink': string;
    'paymentToken': string;
    'price': string;
    'useInvoice': boolean;
}
export declare const ProductCreateRequestCurrencyEnum: {
    readonly Rub: "RUB";
    readonly Usd: "USD";
    readonly Eur: "EUR";
    readonly Xtr: "XTR";
};
export type ProductCreateRequestCurrencyEnum = typeof ProductCreateRequestCurrencyEnum[keyof typeof ProductCreateRequestCurrencyEnum];
export interface ProductListResponseProductsInner {
    'botId': string;
    'currency': ProductListResponseProductsInnerCurrencyEnum;
    'description': string;
    'imageUrl': string;
    'name': string;
    'payLink': string;
    'price': string;
    'productId': string;
    'useInvoice': boolean;
}
export declare const ProductListResponseProductsInnerCurrencyEnum: {
    readonly Rub: "RUB";
    readonly Usd: "USD";
    readonly Eur: "EUR";
    readonly Xtr: "XTR";
};
export type ProductListResponseProductsInnerCurrencyEnum = typeof ProductListResponseProductsInnerCurrencyEnum[keyof typeof ProductListResponseProductsInnerCurrencyEnum];
export interface ProductUpdateRequest {
    'currency': ProductUpdateRequestCurrencyEnum;
    'description': string;
    'imageUrl': string;
    'name': string;
    'payLink': string;
    'paymentToken': string;
    'price': string;
    'useInvoice': boolean;
}
export declare const ProductUpdateRequestCurrencyEnum: {
    readonly Rub: "RUB";
    readonly Usd: "USD";
    readonly Eur: "EUR";
    readonly Xtr: "XTR";
};
export type ProductUpdateRequestCurrencyEnum = typeof ProductUpdateRequestCurrencyEnum[keyof typeof ProductUpdateRequestCurrencyEnum];
export interface PromptPresetListResponsePromptPresetsInner {
    'description': string;
    'name': string;
    'presetId': string;
}
export interface StatisticsGetResponseRecordsInner {
    'timestamp': string;
    'type': StatisticsGetResponseRecordsInnerTypeEnum;
    'value': string;
}
export declare const StatisticsGetResponseRecordsInnerTypeEnum: {
    readonly Messages: "MESSAGES";
    readonly Chats: "CHATS";
    readonly Payments: "PAYMENTS";
};
export type StatisticsGetResponseRecordsInnerTypeEnum = typeof StatisticsGetResponseRecordsInnerTypeEnum[keyof typeof StatisticsGetResponseRecordsInnerTypeEnum];
export interface TransactionBillRequest {
    'amount': string;
}
export interface TransactionsListResponseTransactionsInner {
    'amount': string;
    'timestamp': string;
    'transactionId': string;
    'type': TransactionsListResponseTransactionsInnerTypeEnum;
}
export declare const TransactionsListResponseTransactionsInnerTypeEnum: {
    readonly Deposit: "DEPOSIT";
    readonly Payment: "PAYMENT";
};
export type TransactionsListResponseTransactionsInnerTypeEnum = typeof TransactionsListResponseTransactionsInnerTypeEnum[keyof typeof TransactionsListResponseTransactionsInnerTypeEnum];
/**
 * ControllerApi - axios parameter creator
 */
export declare const ControllerApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @summary Activate telegram bot
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotActivate: (botId: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Register telegram bot on platform
     * @param {BotCreateRequest} botCreateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotCreate: (botCreateRequest: BotCreateRequest, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Deactivate telegram bot
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotDeactivate: (botId: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Delete telegram bot from platform
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotDelete: (botId: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Get telegram bot on platform
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotGet: (botId: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary List all telegram bots on platform
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotList: (options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Update telegram bot on platform
     * @param {string} botId
     * @param {BotUpdateRequest} botUpdateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotUpdate: (botId: string, botUpdateRequest: BotUpdateRequest, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Create product for telegram bot
     * @param {ProductCreateRequest} productCreateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductCreate: (productCreateRequest: ProductCreateRequest, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Delete product for telegram bot
     * @param {string} productId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductDelete: (productId: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Get product for telegram bot
     * @param {string} productId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductGet: (productId: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary List all products for telegram bot
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductList: (botId: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Update product for telegram bot
     * @param {string} productId
     * @param {ProductUpdateRequest} productUpdateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductUpdate: (productId: string, productUpdateRequest: ProductUpdateRequest, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary List of promt presets for telegram bot
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerPromptPresetList: (options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Get statistics for user
     * @param {string} botId
     * @param {string} startTime
     * @param {string} endTime
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerStatisticsGet: (botId: string, startTime: string, endTime: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Deposit transaction
     * @param {TransactionBillRequest} transactionBillRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerTransactionBill: (transactionBillRequest: TransactionBillRequest, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Get transactions
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerTransactionsList: (options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * ControllerApi - functional programming interface
 */
export declare const ControllerApiFp: (configuration?: Configuration) => {
    /**
     *
     * @summary Activate telegram bot
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotActivate(botId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @summary Register telegram bot on platform
     * @param {BotCreateRequest} botCreateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotCreate(botCreateRequest: BotCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Bot>>;
    /**
     *
     * @summary Deactivate telegram bot
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotDeactivate(botId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @summary Delete telegram bot from platform
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotDelete(botId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @summary Get telegram bot on platform
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotGet(botId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Bot>>;
    /**
     *
     * @summary List all telegram bots on platform
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotList(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<BotListResponseBotsInner>>>;
    /**
     *
     * @summary Update telegram bot on platform
     * @param {string} botId
     * @param {BotUpdateRequest} botUpdateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotUpdate(botId: string, botUpdateRequest: BotUpdateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Bot>>;
    /**
     *
     * @summary Create product for telegram bot
     * @param {ProductCreateRequest} productCreateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductCreate(productCreateRequest: ProductCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Product>>;
    /**
     *
     * @summary Delete product for telegram bot
     * @param {string} productId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductDelete(productId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @summary Get product for telegram bot
     * @param {string} productId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductGet(productId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Product>>;
    /**
     *
     * @summary List all products for telegram bot
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductList(botId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ProductListResponseProductsInner>>>;
    /**
     *
     * @summary Update product for telegram bot
     * @param {string} productId
     * @param {ProductUpdateRequest} productUpdateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductUpdate(productId: string, productUpdateRequest: ProductUpdateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Product>>;
    /**
     *
     * @summary List of promt presets for telegram bot
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerPromptPresetList(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PromptPresetListResponsePromptPresetsInner>>>;
    /**
     *
     * @summary Get statistics for user
     * @param {string} botId
     * @param {string} startTime
     * @param {string} endTime
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerStatisticsGet(botId: string, startTime: string, endTime: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<StatisticsGetResponseRecordsInner>>>;
    /**
     *
     * @summary Deposit transaction
     * @param {TransactionBillRequest} transactionBillRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerTransactionBill(transactionBillRequest: TransactionBillRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @summary Get transactions
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerTransactionsList(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TransactionsListResponseTransactionsInner>>>;
};
/**
 * ControllerApi - factory interface
 */
export declare const ControllerApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @summary Activate telegram bot
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotActivate(botId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;
    /**
     *
     * @summary Register telegram bot on platform
     * @param {BotCreateRequest} botCreateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotCreate(botCreateRequest: BotCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<Bot>;
    /**
     *
     * @summary Deactivate telegram bot
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotDeactivate(botId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;
    /**
     *
     * @summary Delete telegram bot from platform
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotDelete(botId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;
    /**
     *
     * @summary Get telegram bot on platform
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotGet(botId: string, options?: RawAxiosRequestConfig): AxiosPromise<Bot>;
    /**
     *
     * @summary List all telegram bots on platform
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotList(options?: RawAxiosRequestConfig): AxiosPromise<Array<BotListResponseBotsInner>>;
    /**
     *
     * @summary Update telegram bot on platform
     * @param {string} botId
     * @param {BotUpdateRequest} botUpdateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotUpdate(botId: string, botUpdateRequest: BotUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<Bot>;
    /**
     *
     * @summary Create product for telegram bot
     * @param {ProductCreateRequest} productCreateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductCreate(productCreateRequest: ProductCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<Product>;
    /**
     *
     * @summary Delete product for telegram bot
     * @param {string} productId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductDelete(productId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;
    /**
     *
     * @summary Get product for telegram bot
     * @param {string} productId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductGet(productId: string, options?: RawAxiosRequestConfig): AxiosPromise<Product>;
    /**
     *
     * @summary List all products for telegram bot
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductList(botId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<ProductListResponseProductsInner>>;
    /**
     *
     * @summary Update product for telegram bot
     * @param {string} productId
     * @param {ProductUpdateRequest} productUpdateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductUpdate(productId: string, productUpdateRequest: ProductUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<Product>;
    /**
     *
     * @summary List of promt presets for telegram bot
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerPromptPresetList(options?: RawAxiosRequestConfig): AxiosPromise<Array<PromptPresetListResponsePromptPresetsInner>>;
    /**
     *
     * @summary Get statistics for user
     * @param {string} botId
     * @param {string} startTime
     * @param {string} endTime
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerStatisticsGet(botId: string, startTime: string, endTime: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<StatisticsGetResponseRecordsInner>>;
    /**
     *
     * @summary Deposit transaction
     * @param {TransactionBillRequest} transactionBillRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerTransactionBill(transactionBillRequest: TransactionBillRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;
    /**
     *
     * @summary Get transactions
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerTransactionsList(options?: RawAxiosRequestConfig): AxiosPromise<Array<TransactionsListResponseTransactionsInner>>;
};
/**
 * ControllerApi - interface
 */
export interface ControllerApiInterface {
    /**
     *
     * @summary Activate telegram bot
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotActivate(botId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;
    /**
     *
     * @summary Register telegram bot on platform
     * @param {BotCreateRequest} botCreateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotCreate(botCreateRequest: BotCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<Bot>;
    /**
     *
     * @summary Deactivate telegram bot
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotDeactivate(botId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;
    /**
     *
     * @summary Delete telegram bot from platform
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotDelete(botId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;
    /**
     *
     * @summary Get telegram bot on platform
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotGet(botId: string, options?: RawAxiosRequestConfig): AxiosPromise<Bot>;
    /**
     *
     * @summary List all telegram bots on platform
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotList(options?: RawAxiosRequestConfig): AxiosPromise<Array<BotListResponseBotsInner>>;
    /**
     *
     * @summary Update telegram bot on platform
     * @param {string} botId
     * @param {BotUpdateRequest} botUpdateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotUpdate(botId: string, botUpdateRequest: BotUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<Bot>;
    /**
     *
     * @summary Create product for telegram bot
     * @param {ProductCreateRequest} productCreateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductCreate(productCreateRequest: ProductCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<Product>;
    /**
     *
     * @summary Delete product for telegram bot
     * @param {string} productId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductDelete(productId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;
    /**
     *
     * @summary Get product for telegram bot
     * @param {string} productId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductGet(productId: string, options?: RawAxiosRequestConfig): AxiosPromise<Product>;
    /**
     *
     * @summary List all products for telegram bot
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductList(botId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<ProductListResponseProductsInner>>;
    /**
     *
     * @summary Update product for telegram bot
     * @param {string} productId
     * @param {ProductUpdateRequest} productUpdateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductUpdate(productId: string, productUpdateRequest: ProductUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<Product>;
    /**
     *
     * @summary List of promt presets for telegram bot
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerPromptPresetList(options?: RawAxiosRequestConfig): AxiosPromise<Array<PromptPresetListResponsePromptPresetsInner>>;
    /**
     *
     * @summary Get statistics for user
     * @param {string} botId
     * @param {string} startTime
     * @param {string} endTime
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerStatisticsGet(botId: string, startTime: string, endTime: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<StatisticsGetResponseRecordsInner>>;
    /**
     *
     * @summary Deposit transaction
     * @param {TransactionBillRequest} transactionBillRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerTransactionBill(transactionBillRequest: TransactionBillRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;
    /**
     *
     * @summary Get transactions
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerTransactionsList(options?: RawAxiosRequestConfig): AxiosPromise<Array<TransactionsListResponseTransactionsInner>>;
}
/**
 * ControllerApi - object-oriented interface
 */
export declare class ControllerApi extends BaseAPI implements ControllerApiInterface {
    /**
     *
     * @summary Activate telegram bot
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotActivate(botId: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @summary Register telegram bot on platform
     * @param {BotCreateRequest} botCreateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotCreate(botCreateRequest: BotCreateRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<Bot, any, {}>>;
    /**
     *
     * @summary Deactivate telegram bot
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotDeactivate(botId: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @summary Delete telegram bot from platform
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotDelete(botId: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @summary Get telegram bot on platform
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotGet(botId: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<Bot, any, {}>>;
    /**
     *
     * @summary List all telegram bots on platform
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotList(options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<BotListResponseBotsInner[], any, {}>>;
    /**
     *
     * @summary Update telegram bot on platform
     * @param {string} botId
     * @param {BotUpdateRequest} botUpdateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotUpdate(botId: string, botUpdateRequest: BotUpdateRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<Bot, any, {}>>;
    /**
     *
     * @summary Create product for telegram bot
     * @param {ProductCreateRequest} productCreateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductCreate(productCreateRequest: ProductCreateRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<Product, any, {}>>;
    /**
     *
     * @summary Delete product for telegram bot
     * @param {string} productId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductDelete(productId: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @summary Get product for telegram bot
     * @param {string} productId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductGet(productId: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<Product, any, {}>>;
    /**
     *
     * @summary List all products for telegram bot
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductList(botId: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<ProductListResponseProductsInner[], any, {}>>;
    /**
     *
     * @summary Update product for telegram bot
     * @param {string} productId
     * @param {ProductUpdateRequest} productUpdateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductUpdate(productId: string, productUpdateRequest: ProductUpdateRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<Product, any, {}>>;
    /**
     *
     * @summary List of promt presets for telegram bot
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerPromptPresetList(options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<PromptPresetListResponsePromptPresetsInner[], any, {}>>;
    /**
     *
     * @summary Get statistics for user
     * @param {string} botId
     * @param {string} startTime
     * @param {string} endTime
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerStatisticsGet(botId: string, startTime: string, endTime: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<StatisticsGetResponseRecordsInner[], any, {}>>;
    /**
     *
     * @summary Deposit transaction
     * @param {TransactionBillRequest} transactionBillRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerTransactionBill(transactionBillRequest: TransactionBillRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @summary Get transactions
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerTransactionsList(options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<TransactionsListResponseTransactionsInner[], any, {}>>;
}
