// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: protobuff/v1.proto

package api

import (
	_ "github.com/merzzzl/proto-rest-api/restapi"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Currency int32

const (
	Currency_RUB Currency = 0
	Currency_USD Currency = 1
	Currency_EUR Currency = 2
	Currency_XTR Currency = 3
)

// Enum value maps for Currency.
var (
	Currency_name = map[int32]string{
		0: "RUB",
		1: "USD",
		2: "EUR",
		3: "XTR",
	}
	Currency_value = map[string]int32{
		"RUB": 0,
		"USD": 1,
		"EUR": 2,
		"XTR": 3,
	}
)

func (x Currency) Enum() *Currency {
	p := new(Currency)
	*p = x
	return p
}

func (x Currency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Currency) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuff_v1_proto_enumTypes[0].Descriptor()
}

func (Currency) Type() protoreflect.EnumType {
	return &file_protobuff_v1_proto_enumTypes[0]
}

func (x Currency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Currency.Descriptor instead.
func (Currency) EnumDescriptor() ([]byte, []int) {
	return file_protobuff_v1_proto_rawDescGZIP(), []int{0}
}

type StatisticType int32

const (
	StatisticType_MESSAGES StatisticType = 0
	StatisticType_CHATS    StatisticType = 1
	StatisticType_PAYMENTS StatisticType = 2
)

// Enum value maps for StatisticType.
var (
	StatisticType_name = map[int32]string{
		0: "MESSAGES",
		1: "CHATS",
		2: "PAYMENTS",
	}
	StatisticType_value = map[string]int32{
		"MESSAGES": 0,
		"CHATS":    1,
		"PAYMENTS": 2,
	}
)

func (x StatisticType) Enum() *StatisticType {
	p := new(StatisticType)
	*p = x
	return p
}

func (x StatisticType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatisticType) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuff_v1_proto_enumTypes[1].Descriptor()
}

func (StatisticType) Type() protoreflect.EnumType {
	return &file_protobuff_v1_proto_enumTypes[1]
}

func (x StatisticType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatisticType.Descriptor instead.
func (StatisticType) EnumDescriptor() ([]byte, []int) {
	return file_protobuff_v1_proto_rawDescGZIP(), []int{1}
}

type TransactionType int32

const (
	TransactionType_DEPOSIT TransactionType = 0
	TransactionType_PAYMENT TransactionType = 1
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0: "DEPOSIT",
		1: "PAYMENT",
	}
	TransactionType_value = map[string]int32{
		"DEPOSIT": 0,
		"PAYMENT": 1,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuff_v1_proto_enumTypes[2].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_protobuff_v1_proto_enumTypes[2]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_protobuff_v1_proto_rawDescGZIP(), []int{2}
}

type BotGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         int64                  `protobuf:"varint,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotGetRequest) Reset() {
	*x = BotGetRequest{}
	mi := &file_protobuff_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotGetRequest) ProtoMessage() {}

func (x *BotGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotGetRequest.ProtoReflect.Descriptor instead.
func (*BotGetRequest) Descriptor() ([]byte, []int) {
	return file_protobuff_v1_proto_rawDescGZIP(), []int{0}
}

func (x *BotGetRequest) GetBotId() int64 {
	if x != nil {
		return x.BotId
	}
	return 0
}

type BotCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotToken      string                 `protobuf:"bytes,1,opt,name=bot_token,json=botToken,proto3" json:"bot_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotCreateRequest) Reset() {
	*x = BotCreateRequest{}
	mi := &file_protobuff_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotCreateRequest) ProtoMessage() {}

func (x *BotCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotCreateRequest.ProtoReflect.Descriptor instead.
func (*BotCreateRequest) Descriptor() ([]byte, []int) {
	return file_protobuff_v1_proto_rawDescGZIP(), []int{1}
}

func (x *BotCreateRequest) GetBotToken() string {
	if x != nil {
		return x.BotToken
	}
	return ""
}

type BotActivateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         int64                  `protobuf:"varint,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotActivateRequest) Reset() {
	*x = BotActivateRequest{}
	mi := &file_protobuff_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotActivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotActivateRequest) ProtoMessage() {}

func (x *BotActivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotActivateRequest.ProtoReflect.Descriptor instead.
func (*BotActivateRequest) Descriptor() ([]byte, []int) {
	return file_protobuff_v1_proto_rawDescGZIP(), []int{2}
}

func (x *BotActivateRequest) GetBotId() int64 {
	if x != nil {
		return x.BotId
	}
	return 0
}

type BotDeactivateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         int64                  `protobuf:"varint,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotDeactivateRequest) Reset() {
	*x = BotDeactivateRequest{}
	mi := &file_protobuff_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotDeactivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotDeactivateRequest) ProtoMessage() {}

func (x *BotDeactivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotDeactivateRequest.ProtoReflect.Descriptor instead.
func (*BotDeactivateRequest) Descriptor() ([]byte, []int) {
	return file_protobuff_v1_proto_rawDescGZIP(), []int{3}
}

func (x *BotDeactivateRequest) GetBotId() int64 {
	if x != nil {
		return x.BotId
	}
	return 0
}

type BotDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         int64                  `protobuf:"varint,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotDeleteRequest) Reset() {
	*x = BotDeleteRequest{}
	mi := &file_protobuff_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotDeleteRequest) ProtoMessage() {}

func (x *BotDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotDeleteRequest.ProtoReflect.Descriptor instead.
func (*BotDeleteRequest) Descriptor() ([]byte, []int) {
	return file_protobuff_v1_proto_rawDescGZIP(), []int{4}
}

func (x *BotDeleteRequest) GetBotId() int64 {
	if x != nil {
		return x.BotId
	}
	return 0
}

type BotUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         int64                  `protobuf:"varint,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	PresetId      int64                  `protobuf:"varint,3,opt,name=preset_id,json=presetId,proto3" json:"preset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotUpdateRequest) Reset() {
	*x = BotUpdateRequest{}
	mi := &file_protobuff_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotUpdateRequest) ProtoMessage() {}

func (x *BotUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotUpdateRequest.ProtoReflect.Descriptor instead.
func (*BotUpdateRequest) Descriptor() ([]byte, []int) {
	return file_protobuff_v1_proto_rawDescGZIP(), []int{5}
}

func (x *BotUpdateRequest) GetBotId() int64 {
	if x != nil {
		return x.BotId
	}
	return 0
}

func (x *BotUpdateRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *BotUpdateRequest) GetPresetId() int64 {
	if x != nil {
		return x.PresetId
	}
	return 0
}

type Bot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         int64                  `protobuf:"varint,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	PresetId      int64                  `protobuf:"varint,5,opt,name=preset_id,json=presetId,proto3" json:"preset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bot) Reset() {
	*x = Bot{}
	mi := &file_protobuff_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bot) ProtoMessage() {}

func (x *Bot) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bot.ProtoReflect.Descriptor instead.
func (*Bot) Descriptor() ([]byte, []int) {
	return file_protobuff_v1_proto_rawDescGZIP(), []int{6}
}

func (x *Bot) GetBotId() int64 {
	if x != nil {
		return x.BotId
	}
	return 0
}

func (x *Bot) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *Bot) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Bot) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Bot) GetPresetId() int64 {
	if x != nil {
		return x.PresetId
	}
	return 0
}

type BotListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bots          []*Bot                 `protobuf:"bytes,1,rep,name=bots,proto3" json:"bots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotListResponse) Reset() {
	*x = BotListResponse{}
	mi := &file_protobuff_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotListResponse) ProtoMessage() {}

func (x *BotListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotListResponse.ProtoReflect.Descriptor instead.
func (*BotListResponse) Descriptor() ([]byte, []int) {
	return file_protobuff_v1_proto_rawDescGZIP(), []int{7}
}

func (x *BotListResponse) GetBots() []*Bot {
	if x != nil {
		return x.Bots
	}
	return nil
}

type ProductGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductGetRequest) Reset() {
	*x = ProductGetRequest{}
	mi := &file_protobuff_v1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductGetRequest) ProtoMessage() {}

func (x *ProductGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_v1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductGetRequest.ProtoReflect.Descriptor instead.
func (*ProductGetRequest) Descriptor() ([]byte, []int) {
	return file_protobuff_v1_proto_rawDescGZIP(), []int{8}
}

func (x *ProductGetRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type ProductCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	PayLink       string                 `protobuf:"bytes,4,opt,name=pay_link,json=payLink,proto3" json:"pay_link,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	BotId         int64                  `protobuf:"varint,6,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	Currency      Currency               `protobuf:"varint,7,opt,name=currency,proto3,enum=api.Currency" json:"currency,omitempty"`
	UseInvoice    bool                   `protobuf:"varint,8,opt,name=use_invoice,json=useInvoice,proto3" json:"use_invoice,omitempty"`
	PaymentToken  string                 `protobuf:"bytes,9,opt,name=payment_token,json=paymentToken,proto3" json:"payment_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductCreateRequest) Reset() {
	*x = ProductCreateRequest{}
	mi := &file_protobuff_v1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductCreateRequest) ProtoMessage() {}

func (x *ProductCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_v1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductCreateRequest.ProtoReflect.Descriptor instead.
func (*ProductCreateRequest) Descriptor() ([]byte, []int) {
	return file_protobuff_v1_proto_rawDescGZIP(), []int{9}
}

func (x *ProductCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductCreateRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductCreateRequest) GetPayLink() string {
	if x != nil {
		return x.PayLink
	}
	return ""
}

func (x *ProductCreateRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ProductCreateRequest) GetBotId() int64 {
	if x != nil {
		return x.BotId
	}
	return 0
}

func (x *ProductCreateRequest) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_RUB
}

func (x *ProductCreateRequest) GetUseInvoice() bool {
	if x != nil {
		return x.UseInvoice
	}
	return false
}

func (x *ProductCreateRequest) GetPaymentToken() string {
	if x != nil {
		return x.PaymentToken
	}
	return ""
}

type ProductDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductDeleteRequest) Reset() {
	*x = ProductDeleteRequest{}
	mi := &file_protobuff_v1_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductDeleteRequest) ProtoMessage() {}

func (x *ProductDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_v1_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductDeleteRequest.ProtoReflect.Descriptor instead.
func (*ProductDeleteRequest) Descriptor() ([]byte, []int) {
	return file_protobuff_v1_proto_rawDescGZIP(), []int{10}
}

func (x *ProductDeleteRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type ProductUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	PayLink       string                 `protobuf:"bytes,5,opt,name=pay_link,json=payLink,proto3" json:"pay_link,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Currency      Currency               `protobuf:"varint,7,opt,name=currency,proto3,enum=api.Currency" json:"currency,omitempty"`
	UseInvoice    bool                   `protobuf:"varint,8,opt,name=use_invoice,json=useInvoice,proto3" json:"use_invoice,omitempty"`
	PaymentToken  string                 `protobuf:"bytes,9,opt,name=payment_token,json=paymentToken,proto3" json:"payment_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductUpdateRequest) Reset() {
	*x = ProductUpdateRequest{}
	mi := &file_protobuff_v1_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductUpdateRequest) ProtoMessage() {}

func (x *ProductUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_v1_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductUpdateRequest.ProtoReflect.Descriptor instead.
func (*ProductUpdateRequest) Descriptor() ([]byte, []int) {
	return file_protobuff_v1_proto_rawDescGZIP(), []int{11}
}

func (x *ProductUpdateRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductUpdateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductUpdateRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductUpdateRequest) GetPayLink() string {
	if x != nil {
		return x.PayLink
	}
	return ""
}

func (x *ProductUpdateRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ProductUpdateRequest) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_RUB
}

func (x *ProductUpdateRequest) GetUseInvoice() bool {
	if x != nil {
		return x.UseInvoice
	}
	return false
}

func (x *ProductUpdateRequest) GetPaymentToken() string {
	if x != nil {
		return x.PaymentToken
	}
	return ""
}

type ProductListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         int64                  `protobuf:"varint,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductListRequest) Reset() {
	*x = ProductListRequest{}
	mi := &file_protobuff_v1_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductListRequest) ProtoMessage() {}

func (x *ProductListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_v1_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductListRequest.ProtoReflect.Descriptor instead.
func (*ProductListRequest) Descriptor() ([]byte, []int) {
	return file_protobuff_v1_proto_rawDescGZIP(), []int{12}
}

func (x *ProductListRequest) GetBotId() int64 {
	if x != nil {
		return x.BotId
	}
	return 0
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	PayLink       string                 `protobuf:"bytes,5,opt,name=pay_link,json=payLink,proto3" json:"pay_link,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	BotId         int64                  `protobuf:"varint,7,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	Currency      Currency               `protobuf:"varint,8,opt,name=currency,proto3,enum=api.Currency" json:"currency,omitempty"`
	UseInvoice    bool                   `protobuf:"varint,9,opt,name=use_invoice,json=useInvoice,proto3" json:"use_invoice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_protobuff_v1_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_v1_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_protobuff_v1_proto_rawDescGZIP(), []int{13}
}

func (x *Product) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetPayLink() string {
	if x != nil {
		return x.PayLink
	}
	return ""
}

func (x *Product) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Product) GetBotId() int64 {
	if x != nil {
		return x.BotId
	}
	return 0
}

func (x *Product) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_RUB
}

func (x *Product) GetUseInvoice() bool {
	if x != nil {
		return x.UseInvoice
	}
	return false
}

type ProductListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductListResponse) Reset() {
	*x = ProductListResponse{}
	mi := &file_protobuff_v1_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductListResponse) ProtoMessage() {}

func (x *ProductListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_v1_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductListResponse.ProtoReflect.Descriptor instead.
func (*ProductListResponse) Descriptor() ([]byte, []int) {
	return file_protobuff_v1_proto_rawDescGZIP(), []int{14}
}

func (x *ProductListResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type PromptPreset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PresetId      int64                  `protobuf:"varint,1,opt,name=preset_id,json=presetId,proto3" json:"preset_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptPreset) Reset() {
	*x = PromptPreset{}
	mi := &file_protobuff_v1_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptPreset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptPreset) ProtoMessage() {}

func (x *PromptPreset) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_v1_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptPreset.ProtoReflect.Descriptor instead.
func (*PromptPreset) Descriptor() ([]byte, []int) {
	return file_protobuff_v1_proto_rawDescGZIP(), []int{15}
}

func (x *PromptPreset) GetPresetId() int64 {
	if x != nil {
		return x.PresetId
	}
	return 0
}

func (x *PromptPreset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PromptPreset) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PromptPresetListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PromptPresets []*PromptPreset        `protobuf:"bytes,1,rep,name=prompt_presets,json=promptPresets,proto3" json:"prompt_presets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptPresetListResponse) Reset() {
	*x = PromptPresetListResponse{}
	mi := &file_protobuff_v1_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptPresetListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptPresetListResponse) ProtoMessage() {}

func (x *PromptPresetListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_v1_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptPresetListResponse.ProtoReflect.Descriptor instead.
func (*PromptPresetListResponse) Descriptor() ([]byte, []int) {
	return file_protobuff_v1_proto_rawDescGZIP(), []int{16}
}

func (x *PromptPresetListResponse) GetPromptPresets() []*PromptPreset {
	if x != nil {
		return x.PromptPresets
	}
	return nil
}

type StatisticsGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     int64                  `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	BotId         int64                  `protobuf:"varint,3,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticsGetRequest) Reset() {
	*x = StatisticsGetRequest{}
	mi := &file_protobuff_v1_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsGetRequest) ProtoMessage() {}

func (x *StatisticsGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_v1_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsGetRequest.ProtoReflect.Descriptor instead.
func (*StatisticsGetRequest) Descriptor() ([]byte, []int) {
	return file_protobuff_v1_proto_rawDescGZIP(), []int{17}
}

func (x *StatisticsGetRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *StatisticsGetRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *StatisticsGetRequest) GetBotId() int64 {
	if x != nil {
		return x.BotId
	}
	return 0
}

type StatisticsGetResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Records       []*StatisticsGetResponse_Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticsGetResponse) Reset() {
	*x = StatisticsGetResponse{}
	mi := &file_protobuff_v1_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsGetResponse) ProtoMessage() {}

func (x *StatisticsGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_v1_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsGetResponse.ProtoReflect.Descriptor instead.
func (*StatisticsGetResponse) Descriptor() ([]byte, []int) {
	return file_protobuff_v1_proto_rawDescGZIP(), []int{18}
}

func (x *StatisticsGetResponse) GetRecords() []*StatisticsGetResponse_Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type TransactionsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionsListResponse) Reset() {
	*x = TransactionsListResponse{}
	mi := &file_protobuff_v1_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionsListResponse) ProtoMessage() {}

func (x *TransactionsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_v1_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionsListResponse.ProtoReflect.Descriptor instead.
func (*TransactionsListResponse) Descriptor() ([]byte, []int) {
	return file_protobuff_v1_proto_rawDescGZIP(), []int{19}
}

func (x *TransactionsListResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId int64                  `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Type          TransactionType        `protobuf:"varint,3,opt,name=type,proto3,enum=api.TransactionType" json:"type,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_protobuff_v1_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_v1_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_protobuff_v1_proto_rawDescGZIP(), []int{20}
}

func (x *Transaction) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *Transaction) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetType() TransactionType {
	if x != nil {
		return x.Type
	}
	return TransactionType_DEPOSIT
}

func (x *Transaction) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type TransactionBillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionBillRequest) Reset() {
	*x = TransactionBillRequest{}
	mi := &file_protobuff_v1_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionBillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionBillRequest) ProtoMessage() {}

func (x *TransactionBillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_v1_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionBillRequest.ProtoReflect.Descriptor instead.
func (*TransactionBillRequest) Descriptor() ([]byte, []int) {
	return file_protobuff_v1_proto_rawDescGZIP(), []int{21}
}

func (x *TransactionBillRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type StatisticsGetResponse_Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          StatisticType          `protobuf:"varint,1,opt,name=type,proto3,enum=api.StatisticType" json:"type,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticsGetResponse_Record) Reset() {
	*x = StatisticsGetResponse_Record{}
	mi := &file_protobuff_v1_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsGetResponse_Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsGetResponse_Record) ProtoMessage() {}

func (x *StatisticsGetResponse_Record) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_v1_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsGetResponse_Record.ProtoReflect.Descriptor instead.
func (*StatisticsGetResponse_Record) Descriptor() ([]byte, []int) {
	return file_protobuff_v1_proto_rawDescGZIP(), []int{18, 0}
}

func (x *StatisticsGetResponse_Record) GetType() StatisticType {
	if x != nil {
		return x.Type
	}
	return StatisticType_MESSAGES
}

func (x *StatisticsGetResponse_Record) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *StatisticsGetResponse_Record) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_protobuff_v1_proto protoreflect.FileDescriptor

const file_protobuff_v1_proto_rawDesc = "" +
	"\n" +
	"\x12protobuff/v1.proto\x12\x03api\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19restapi/annotations.proto\"&\n" +
	"\rBotGetRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\x03R\x05botId\"/\n" +
	"\x10BotCreateRequest\x12\x1b\n" +
	"\tbot_token\x18\x01 \x01(\tR\bbotToken\"+\n" +
	"\x12BotActivateRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\x03R\x05botId\"-\n" +
	"\x14BotDeactivateRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\x03R\x05botId\")\n" +
	"\x10BotDeleteRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\x03R\x05botId\"^\n" +
	"\x10BotUpdateRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\x03R\x05botId\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x1b\n" +
	"\tpreset_id\x18\x03 \x01(\x03R\bpresetId\"\x7f\n" +
	"\x03Bot\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\x03R\x05botId\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12\x1b\n" +
	"\tpreset_id\x18\x05 \x01(\x03R\bpresetId\"/\n" +
	"\x0fBotListResponse\x12\x1c\n" +
	"\x04bots\x18\x01 \x03(\v2\b.api.BotR\x04bots\"2\n" +
	"\x11ProductGetRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\"\xa2\x02\n" +
	"\x14ProductCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x19\n" +
	"\bpay_link\x18\x04 \x01(\tR\apayLink\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x12\x15\n" +
	"\x06bot_id\x18\x06 \x01(\x03R\x05botId\x12)\n" +
	"\bcurrency\x18\a \x01(\x0e2\r.api.CurrencyR\bcurrency\x12\x1f\n" +
	"\vuse_invoice\x18\b \x01(\bR\n" +
	"useInvoice\x12#\n" +
	"\rpayment_token\x18\t \x01(\tR\fpaymentToken\"5\n" +
	"\x14ProductDeleteRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\"\xaa\x02\n" +
	"\x14ProductUpdateRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x19\n" +
	"\bpay_link\x18\x05 \x01(\tR\apayLink\x12\x1b\n" +
	"\timage_url\x18\x06 \x01(\tR\bimageUrl\x12)\n" +
	"\bcurrency\x18\a \x01(\x0e2\r.api.CurrencyR\bcurrency\x12\x1f\n" +
	"\vuse_invoice\x18\b \x01(\bR\n" +
	"useInvoice\x12#\n" +
	"\rpayment_token\x18\t \x01(\tR\fpaymentToken\"+\n" +
	"\x12ProductListRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\x03R\x05botId\"\x8f\x02\n" +
	"\aProduct\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x19\n" +
	"\bpay_link\x18\x05 \x01(\tR\apayLink\x12\x1b\n" +
	"\timage_url\x18\x06 \x01(\tR\bimageUrl\x12\x15\n" +
	"\x06bot_id\x18\a \x01(\x03R\x05botId\x12)\n" +
	"\bcurrency\x18\b \x01(\x0e2\r.api.CurrencyR\bcurrency\x12\x1f\n" +
	"\vuse_invoice\x18\t \x01(\bR\n" +
	"useInvoice\"?\n" +
	"\x13ProductListResponse\x12(\n" +
	"\bproducts\x18\x01 \x03(\v2\f.api.ProductR\bproducts\"a\n" +
	"\fPromptPreset\x12\x1b\n" +
	"\tpreset_id\x18\x01 \x01(\x03R\bpresetId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"T\n" +
	"\x18PromptPresetListResponse\x128\n" +
	"\x0eprompt_presets\x18\x01 \x03(\v2\x11.api.PromptPresetR\rpromptPresets\"g\n" +
	"\x14StatisticsGetRequest\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\x03R\aendTime\x12\x15\n" +
	"\x06bot_id\x18\x03 \x01(\x03R\x05botId\"\xba\x01\n" +
	"\x15StatisticsGetResponse\x12;\n" +
	"\arecords\x18\x01 \x03(\v2!.api.StatisticsGetResponse.RecordR\arecords\x1ad\n" +
	"\x06Record\x12&\n" +
	"\x04type\x18\x01 \x01(\x0e2\x12.api.StatisticTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"P\n" +
	"\x18TransactionsListResponse\x124\n" +
	"\ftransactions\x18\x01 \x03(\v2\x10.api.TransactionR\ftransactions\"\x94\x01\n" +
	"\vTransaction\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\x03R\rtransactionId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12(\n" +
	"\x04type\x18\x03 \x01(\x0e2\x14.api.TransactionTypeR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"0\n" +
	"\x16TransactionBillRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount*.\n" +
	"\bCurrency\x12\a\n" +
	"\x03RUB\x10\x00\x12\a\n" +
	"\x03USD\x10\x01\x12\a\n" +
	"\x03EUR\x10\x02\x12\a\n" +
	"\x03XTR\x10\x03*6\n" +
	"\rStatisticType\x12\f\n" +
	"\bMESSAGES\x10\x00\x12\t\n" +
	"\x05CHATS\x10\x01\x12\f\n" +
	"\bPAYMENTS\x10\x02*+\n" +
	"\x0fTransactionType\x12\v\n" +
	"\aDEPOSIT\x10\x00\x12\v\n" +
	"\aPAYMENT\x10\x012\xbd\f\n" +
	"\n" +
	"Controller\x12E\n" +
	"\tBotCreate\x12\x15.api.BotCreateRequest\x1a\b.api.Bot\"\x17\x8a\x97\"\x13\n" +
	"\x04POST\x12\x05/bots\x1a\x01*\"\x01*\x12b\n" +
	"\vBotActivate\x12\x17.api.BotActivateRequest\x1a\x16.google.protobuf.Empty\"\"\x8a\x97\"\x1e\n" +
	"\x04POST\x12\x16/bots/:bot_id/activate\x12h\n" +
	"\rBotDeactivate\x12\x19.api.BotDeactivateRequest\x1a\x16.google.protobuf.Empty\"$\x8a\x97\" \n" +
	"\x04POST\x12\x18/bots/:bot_id/deactivate\x12W\n" +
	"\tBotDelete\x12\x15.api.BotDeleteRequest\x1a\x16.google.protobuf.Empty\"\x1b\x8a\x97\"\x17\n" +
	"\x06DELETE\x12\r/bots/:bot_id\x12P\n" +
	"\aBotList\x12\x16.google.protobuf.Empty\x1a\x14.api.BotListResponse\"\x17\x8a\x97\"\x13\n" +
	"\x03GET\x12\x05/bots\"\x05.bots\x12L\n" +
	"\tBotUpdate\x12\x15.api.BotUpdateRequest\x1a\b.api.Bot\"\x1e\x8a\x97\"\x1a\n" +
	"\x03PUT\x12\r/bots/:bot_id\x1a\x01*\"\x01*\x12C\n" +
	"\x06BotGet\x12\x12.api.BotGetRequest\x1a\b.api.Bot\"\x1b\x8a\x97\"\x17\n" +
	"\x03GET\x12\r/bots/:bot_id\"\x01*\x12U\n" +
	"\rProductCreate\x12\x19.api.ProductCreateRequest\x1a\f.api.Product\"\x1b\x8a\x97\"\x17\n" +
	"\x04POST\x12\t/products\x1a\x01*\"\x01*\x12g\n" +
	"\rProductDelete\x12\x19.api.ProductDeleteRequest\x1a\x16.google.protobuf.Empty\"#\x8a\x97\"\x1f\n" +
	"\x06DELETE\x12\x15/products/:product_id\x12i\n" +
	"\vProductList\x12\x17.api.ProductListRequest\x1a\x18.api.ProductListResponse\"'\x8a\x97\"#\n" +
	"\x03GET\x12\x11/products?:bot_id\"\t.products\x12`\n" +
	"\rProductUpdate\x12\x19.api.ProductUpdateRequest\x1a\f.api.Product\"&\x8a\x97\"\"\n" +
	"\x03PUT\x12\x15/products/:product_id\x1a\x01*\"\x01*\x12W\n" +
	"\n" +
	"ProductGet\x12\x16.api.ProductGetRequest\x1a\f.api.Product\"#\x8a\x97\"\x1f\n" +
	"\x03GET\x12\x15/products/:product_id\"\x01*\x12\x7f\n" +
	"\x10PromptPresetList\x12\x16.google.protobuf.Empty\x1a\x1d.api.PromptPresetListResponse\"4\x8a\x97\"0\n" +
	"\x03GET\x12\x18/settings/prompt-presets\"\x0f.prompt_presets\x12\x86\x01\n" +
	"\rStatisticsGet\x12\x19.api.StatisticsGetRequest\x1a\x1a.api.StatisticsGetResponse\">\x8a\x97\":\n" +
	"\x03GET\x12)/statistics?:bot_id&:start_time&:end_time\"\b.records\x12r\n" +
	"\x10TransactionsList\x12\x16.google.protobuf.Empty\x1a\x1d.api.TransactionsListResponse\"'\x8a\x97\"#\n" +
	"\x03GET\x12\r/transactions\"\r.transactions\x12i\n" +
	"\x0fTransactionBill\x12\x1b.api.TransactionBillRequest\x1a\x16.google.protobuf.Empty\"!\x8a\x97\"\x1d\n" +
	"\x04POST\x12\x12/transactions/bill\x1a\x01*\x1a\r\x92\x97\"\t\n" +
	"\a/api/v1B\vZ\t./api;apib\x06proto3"

var (
	file_protobuff_v1_proto_rawDescOnce sync.Once
	file_protobuff_v1_proto_rawDescData []byte
)

func file_protobuff_v1_proto_rawDescGZIP() []byte {
	file_protobuff_v1_proto_rawDescOnce.Do(func() {
		file_protobuff_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuff_v1_proto_rawDesc), len(file_protobuff_v1_proto_rawDesc)))
	})
	return file_protobuff_v1_proto_rawDescData
}

var file_protobuff_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_protobuff_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_protobuff_v1_proto_goTypes = []any{
	(Currency)(0),                        // 0: api.Currency
	(StatisticType)(0),                   // 1: api.StatisticType
	(TransactionType)(0),                 // 2: api.TransactionType
	(*BotGetRequest)(nil),                // 3: api.BotGetRequest
	(*BotCreateRequest)(nil),             // 4: api.BotCreateRequest
	(*BotActivateRequest)(nil),           // 5: api.BotActivateRequest
	(*BotDeactivateRequest)(nil),         // 6: api.BotDeactivateRequest
	(*BotDeleteRequest)(nil),             // 7: api.BotDeleteRequest
	(*BotUpdateRequest)(nil),             // 8: api.BotUpdateRequest
	(*Bot)(nil),                          // 9: api.Bot
	(*BotListResponse)(nil),              // 10: api.BotListResponse
	(*ProductGetRequest)(nil),            // 11: api.ProductGetRequest
	(*ProductCreateRequest)(nil),         // 12: api.ProductCreateRequest
	(*ProductDeleteRequest)(nil),         // 13: api.ProductDeleteRequest
	(*ProductUpdateRequest)(nil),         // 14: api.ProductUpdateRequest
	(*ProductListRequest)(nil),           // 15: api.ProductListRequest
	(*Product)(nil),                      // 16: api.Product
	(*ProductListResponse)(nil),          // 17: api.ProductListResponse
	(*PromptPreset)(nil),                 // 18: api.PromptPreset
	(*PromptPresetListResponse)(nil),     // 19: api.PromptPresetListResponse
	(*StatisticsGetRequest)(nil),         // 20: api.StatisticsGetRequest
	(*StatisticsGetResponse)(nil),        // 21: api.StatisticsGetResponse
	(*TransactionsListResponse)(nil),     // 22: api.TransactionsListResponse
	(*Transaction)(nil),                  // 23: api.Transaction
	(*TransactionBillRequest)(nil),       // 24: api.TransactionBillRequest
	(*StatisticsGetResponse_Record)(nil), // 25: api.StatisticsGetResponse.Record
	(*emptypb.Empty)(nil),                // 26: google.protobuf.Empty
}
var file_protobuff_v1_proto_depIdxs = []int32{
	9,  // 0: api.BotListResponse.bots:type_name -> api.Bot
	0,  // 1: api.ProductCreateRequest.currency:type_name -> api.Currency
	0,  // 2: api.ProductUpdateRequest.currency:type_name -> api.Currency
	0,  // 3: api.Product.currency:type_name -> api.Currency
	16, // 4: api.ProductListResponse.products:type_name -> api.Product
	18, // 5: api.PromptPresetListResponse.prompt_presets:type_name -> api.PromptPreset
	25, // 6: api.StatisticsGetResponse.records:type_name -> api.StatisticsGetResponse.Record
	23, // 7: api.TransactionsListResponse.transactions:type_name -> api.Transaction
	2,  // 8: api.Transaction.type:type_name -> api.TransactionType
	1,  // 9: api.StatisticsGetResponse.Record.type:type_name -> api.StatisticType
	4,  // 10: api.Controller.BotCreate:input_type -> api.BotCreateRequest
	5,  // 11: api.Controller.BotActivate:input_type -> api.BotActivateRequest
	6,  // 12: api.Controller.BotDeactivate:input_type -> api.BotDeactivateRequest
	7,  // 13: api.Controller.BotDelete:input_type -> api.BotDeleteRequest
	26, // 14: api.Controller.BotList:input_type -> google.protobuf.Empty
	8,  // 15: api.Controller.BotUpdate:input_type -> api.BotUpdateRequest
	3,  // 16: api.Controller.BotGet:input_type -> api.BotGetRequest
	12, // 17: api.Controller.ProductCreate:input_type -> api.ProductCreateRequest
	13, // 18: api.Controller.ProductDelete:input_type -> api.ProductDeleteRequest
	15, // 19: api.Controller.ProductList:input_type -> api.ProductListRequest
	14, // 20: api.Controller.ProductUpdate:input_type -> api.ProductUpdateRequest
	11, // 21: api.Controller.ProductGet:input_type -> api.ProductGetRequest
	26, // 22: api.Controller.PromptPresetList:input_type -> google.protobuf.Empty
	20, // 23: api.Controller.StatisticsGet:input_type -> api.StatisticsGetRequest
	26, // 24: api.Controller.TransactionsList:input_type -> google.protobuf.Empty
	24, // 25: api.Controller.TransactionBill:input_type -> api.TransactionBillRequest
	9,  // 26: api.Controller.BotCreate:output_type -> api.Bot
	26, // 27: api.Controller.BotActivate:output_type -> google.protobuf.Empty
	26, // 28: api.Controller.BotDeactivate:output_type -> google.protobuf.Empty
	26, // 29: api.Controller.BotDelete:output_type -> google.protobuf.Empty
	10, // 30: api.Controller.BotList:output_type -> api.BotListResponse
	9,  // 31: api.Controller.BotUpdate:output_type -> api.Bot
	9,  // 32: api.Controller.BotGet:output_type -> api.Bot
	16, // 33: api.Controller.ProductCreate:output_type -> api.Product
	26, // 34: api.Controller.ProductDelete:output_type -> google.protobuf.Empty
	17, // 35: api.Controller.ProductList:output_type -> api.ProductListResponse
	16, // 36: api.Controller.ProductUpdate:output_type -> api.Product
	16, // 37: api.Controller.ProductGet:output_type -> api.Product
	19, // 38: api.Controller.PromptPresetList:output_type -> api.PromptPresetListResponse
	21, // 39: api.Controller.StatisticsGet:output_type -> api.StatisticsGetResponse
	22, // 40: api.Controller.TransactionsList:output_type -> api.TransactionsListResponse
	26, // 41: api.Controller.TransactionBill:output_type -> google.protobuf.Empty
	26, // [26:42] is the sub-list for method output_type
	10, // [10:26] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_protobuff_v1_proto_init() }
func file_protobuff_v1_proto_init() {
	if File_protobuff_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuff_v1_proto_rawDesc), len(file_protobuff_v1_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuff_v1_proto_goTypes,
		DependencyIndexes: file_protobuff_v1_proto_depIdxs,
		EnumInfos:         file_protobuff_v1_proto_enumTypes,
		MessageInfos:      file_protobuff_v1_proto_msgTypes,
	}.Build()
	File_protobuff_v1_proto = out.File
	file_protobuff_v1_proto_goTypes = nil
	file_protobuff_v1_proto_depIdxs = nil
}
