// Code generated by protoc-gen-go-rest. DO NOT EDIT.
// versions:
// - protoc-gen-go-rest v0.0.0-alpha.0
// - protoc             v5.29.3
// source: protobuff/v1.proto

package api

import (
	embed "embed"
)

//go:embed v1_swagger.json
var swaggerFile embed.FS

func GetV1Swagger() []byte {
	js, err := swaggerFile.ReadFile("v1_swagger.json")
	if err != nil {
		return []byte("{}")
	}

	return js
}
