/* tslint:disable */
/* eslint-disable */
/**
 * Swagger API (api)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20260216
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface Bot {
    'active': boolean;
    'botId': string;
    'presetId': string;
    'prompt': string;
    'token': string;
}
export interface BotCreateRequest {
    'botToken': string;
}
export interface BotListResponseBotsInner {
    'active': boolean;
    'botId': string;
    'presetId': string;
    'prompt': string;
    'token': string;
}
export interface BotUpdateRequest {
    'presetId': string;
    'prompt': string;
}
export interface Product {
    'botId': string;
    'currency': ProductCurrencyEnum;
    'description': string;
    'imageUrl': string;
    'name': string;
    'payLink': string;
    'price': string;
    'productId': string;
    'useInvoice': boolean;
}

export const ProductCurrencyEnum = {
    Rub: 'RUB',
    Usd: 'USD',
    Eur: 'EUR',
    Xtr: 'XTR',
} as const;

export type ProductCurrencyEnum = typeof ProductCurrencyEnum[keyof typeof ProductCurrencyEnum];

export interface ProductCreateRequest {
    'botId': string;
    'currency': ProductCreateRequestCurrencyEnum;
    'description': string;
    'imageUrl': string;
    'name': string;
    'payLink': string;
    'paymentToken': string;
    'price': string;
    'useInvoice': boolean;
}

export const ProductCreateRequestCurrencyEnum = {
    Rub: 'RUB',
    Usd: 'USD',
    Eur: 'EUR',
    Xtr: 'XTR',
} as const;

export type ProductCreateRequestCurrencyEnum = typeof ProductCreateRequestCurrencyEnum[keyof typeof ProductCreateRequestCurrencyEnum];

export interface ProductListResponseProductsInner {
    'botId': string;
    'currency': ProductListResponseProductsInnerCurrencyEnum;
    'description': string;
    'imageUrl': string;
    'name': string;
    'payLink': string;
    'price': string;
    'productId': string;
    'useInvoice': boolean;
}

export const ProductListResponseProductsInnerCurrencyEnum = {
    Rub: 'RUB',
    Usd: 'USD',
    Eur: 'EUR',
    Xtr: 'XTR',
} as const;

export type ProductListResponseProductsInnerCurrencyEnum = typeof ProductListResponseProductsInnerCurrencyEnum[keyof typeof ProductListResponseProductsInnerCurrencyEnum];

export interface ProductUpdateRequest {
    'currency': ProductUpdateRequestCurrencyEnum;
    'description': string;
    'imageUrl': string;
    'name': string;
    'payLink': string;
    'paymentToken': string;
    'price': string;
    'useInvoice': boolean;
}

export const ProductUpdateRequestCurrencyEnum = {
    Rub: 'RUB',
    Usd: 'USD',
    Eur: 'EUR',
    Xtr: 'XTR',
} as const;

export type ProductUpdateRequestCurrencyEnum = typeof ProductUpdateRequestCurrencyEnum[keyof typeof ProductUpdateRequestCurrencyEnum];

export interface PromptPresetListResponsePromptPresetsInner {
    'description': string;
    'name': string;
    'presetId': string;
}
export interface StatisticsGetResponseRecordsInner {
    'timestamp': string;
    'type': StatisticsGetResponseRecordsInnerTypeEnum;
    'value': string;
}

export const StatisticsGetResponseRecordsInnerTypeEnum = {
    Messages: 'MESSAGES',
    Chats: 'CHATS',
    Payments: 'PAYMENTS',
} as const;

export type StatisticsGetResponseRecordsInnerTypeEnum = typeof StatisticsGetResponseRecordsInnerTypeEnum[keyof typeof StatisticsGetResponseRecordsInnerTypeEnum];

export interface TransactionBillRequest {
    'amount': string;
}
export interface TransactionsListResponseTransactionsInner {
    'amount': string;
    'timestamp': string;
    'transactionId': string;
    'type': TransactionsListResponseTransactionsInnerTypeEnum;
}

export const TransactionsListResponseTransactionsInnerTypeEnum = {
    Deposit: 'DEPOSIT',
    Payment: 'PAYMENT',
} as const;

export type TransactionsListResponseTransactionsInnerTypeEnum = typeof TransactionsListResponseTransactionsInnerTypeEnum[keyof typeof TransactionsListResponseTransactionsInnerTypeEnum];


/**
 * ControllerApi - axios parameter creator
 */
export const ControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         *
         * @summary Activate telegram bot
         * @param {string} botId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerBotActivate: async (botId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'botId' is not null or undefined
            assertParamExists('controllerBotActivate', 'botId', botId)
            const localVarPath = `/api/v1/bots/{bot_id}/activate`
                .replace('{bot_id}', encodeURIComponent(String(botId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Register telegram bot on platform
         * @param {BotCreateRequest} botCreateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerBotCreate: async (botCreateRequest: BotCreateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'botCreateRequest' is not null or undefined
            assertParamExists('controllerBotCreate', 'botCreateRequest', botCreateRequest)
            const localVarPath = `/api/v1/bots`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(botCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Deactivate telegram bot
         * @param {string} botId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerBotDeactivate: async (botId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'botId' is not null or undefined
            assertParamExists('controllerBotDeactivate', 'botId', botId)
            const localVarPath = `/api/v1/bots/{bot_id}/deactivate`
                .replace('{bot_id}', encodeURIComponent(String(botId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Delete telegram bot from platform
         * @param {string} botId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerBotDelete: async (botId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'botId' is not null or undefined
            assertParamExists('controllerBotDelete', 'botId', botId)
            const localVarPath = `/api/v1/bots/{bot_id}`
                .replace('{bot_id}', encodeURIComponent(String(botId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Get telegram bot on platform
         * @param {string} botId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerBotGet: async (botId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'botId' is not null or undefined
            assertParamExists('controllerBotGet', 'botId', botId)
            const localVarPath = `/api/v1/bots/{bot_id}`
                .replace('{bot_id}', encodeURIComponent(String(botId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary List all telegram bots on platform
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerBotList: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/bots`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Update telegram bot on platform
         * @param {string} botId
         * @param {BotUpdateRequest} botUpdateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerBotUpdate: async (botId: string, botUpdateRequest: BotUpdateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'botId' is not null or undefined
            assertParamExists('controllerBotUpdate', 'botId', botId)
            // verify required parameter 'botUpdateRequest' is not null or undefined
            assertParamExists('controllerBotUpdate', 'botUpdateRequest', botUpdateRequest)
            const localVarPath = `/api/v1/bots/{bot_id}`
                .replace('{bot_id}', encodeURIComponent(String(botId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(botUpdateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Create product for telegram bot
         * @param {ProductCreateRequest} productCreateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerProductCreate: async (productCreateRequest: ProductCreateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productCreateRequest' is not null or undefined
            assertParamExists('controllerProductCreate', 'productCreateRequest', productCreateRequest)
            const localVarPath = `/api/v1/products`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(productCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Delete product for telegram bot
         * @param {string} productId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerProductDelete: async (productId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('controllerProductDelete', 'productId', productId)
            const localVarPath = `/api/v1/products/{product_id}`
                .replace('{product_id}', encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Get product for telegram bot
         * @param {string} productId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerProductGet: async (productId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('controllerProductGet', 'productId', productId)
            const localVarPath = `/api/v1/products/{product_id}`
                .replace('{product_id}', encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary List all products for telegram bot
         * @param {string} botId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerProductList: async (botId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'botId' is not null or undefined
            assertParamExists('controllerProductList', 'botId', botId)
            const localVarPath = `/api/v1/products`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (botId !== undefined) {
                localVarQueryParameter['bot_id'] = botId;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Update product for telegram bot
         * @param {string} productId
         * @param {ProductUpdateRequest} productUpdateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerProductUpdate: async (productId: string, productUpdateRequest: ProductUpdateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('controllerProductUpdate', 'productId', productId)
            // verify required parameter 'productUpdateRequest' is not null or undefined
            assertParamExists('controllerProductUpdate', 'productUpdateRequest', productUpdateRequest)
            const localVarPath = `/api/v1/products/{product_id}`
                .replace('{product_id}', encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(productUpdateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary List of promt presets for telegram bot
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerPromptPresetList: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/settings/prompt-presets`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Get statistics for user
         * @param {string} botId
         * @param {string} startTime
         * @param {string} endTime
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerStatisticsGet: async (botId: string, startTime: string, endTime: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'botId' is not null or undefined
            assertParamExists('controllerStatisticsGet', 'botId', botId)
            // verify required parameter 'startTime' is not null or undefined
            assertParamExists('controllerStatisticsGet', 'startTime', startTime)
            // verify required parameter 'endTime' is not null or undefined
            assertParamExists('controllerStatisticsGet', 'endTime', endTime)
            const localVarPath = `/api/v1/statistics`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (botId !== undefined) {
                localVarQueryParameter['bot_id'] = botId;
            }

            if (startTime !== undefined) {
                localVarQueryParameter['start_time'] = startTime;
            }

            if (endTime !== undefined) {
                localVarQueryParameter['end_time'] = endTime;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Deposit transaction
         * @param {TransactionBillRequest} transactionBillRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerTransactionBill: async (transactionBillRequest: TransactionBillRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'transactionBillRequest' is not null or undefined
            assertParamExists('controllerTransactionBill', 'transactionBillRequest', transactionBillRequest)
            const localVarPath = `/api/v1/transactions/bill`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(transactionBillRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Get transactions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerTransactionsList: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/transactions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ControllerApi - functional programming interface
 */
export const ControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ControllerApiAxiosParamCreator(configuration)
    return {
        /**
         *
         * @summary Activate telegram bot
         * @param {string} botId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controllerBotActivate(botId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controllerBotActivate(botId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControllerApi.controllerBotActivate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Register telegram bot on platform
         * @param {BotCreateRequest} botCreateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controllerBotCreate(botCreateRequest: BotCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Bot>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controllerBotCreate(botCreateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControllerApi.controllerBotCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Deactivate telegram bot
         * @param {string} botId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controllerBotDeactivate(botId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controllerBotDeactivate(botId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControllerApi.controllerBotDeactivate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Delete telegram bot from platform
         * @param {string} botId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controllerBotDelete(botId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controllerBotDelete(botId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControllerApi.controllerBotDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Get telegram bot on platform
         * @param {string} botId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controllerBotGet(botId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Bot>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controllerBotGet(botId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControllerApi.controllerBotGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary List all telegram bots on platform
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controllerBotList(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<BotListResponseBotsInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controllerBotList(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControllerApi.controllerBotList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Update telegram bot on platform
         * @param {string} botId
         * @param {BotUpdateRequest} botUpdateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controllerBotUpdate(botId: string, botUpdateRequest: BotUpdateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Bot>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controllerBotUpdate(botId, botUpdateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControllerApi.controllerBotUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Create product for telegram bot
         * @param {ProductCreateRequest} productCreateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controllerProductCreate(productCreateRequest: ProductCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Product>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controllerProductCreate(productCreateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControllerApi.controllerProductCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Delete product for telegram bot
         * @param {string} productId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controllerProductDelete(productId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controllerProductDelete(productId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControllerApi.controllerProductDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Get product for telegram bot
         * @param {string} productId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controllerProductGet(productId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Product>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controllerProductGet(productId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControllerApi.controllerProductGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary List all products for telegram bot
         * @param {string} botId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controllerProductList(botId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ProductListResponseProductsInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controllerProductList(botId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControllerApi.controllerProductList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Update product for telegram bot
         * @param {string} productId
         * @param {ProductUpdateRequest} productUpdateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controllerProductUpdate(productId: string, productUpdateRequest: ProductUpdateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Product>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controllerProductUpdate(productId, productUpdateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControllerApi.controllerProductUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary List of promt presets for telegram bot
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controllerPromptPresetList(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PromptPresetListResponsePromptPresetsInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controllerPromptPresetList(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControllerApi.controllerPromptPresetList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Get statistics for user
         * @param {string} botId
         * @param {string} startTime
         * @param {string} endTime
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controllerStatisticsGet(botId: string, startTime: string, endTime: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<StatisticsGetResponseRecordsInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controllerStatisticsGet(botId, startTime, endTime, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControllerApi.controllerStatisticsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Deposit transaction
         * @param {TransactionBillRequest} transactionBillRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controllerTransactionBill(transactionBillRequest: TransactionBillRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controllerTransactionBill(transactionBillRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControllerApi.controllerTransactionBill']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Get transactions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controllerTransactionsList(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TransactionsListResponseTransactionsInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controllerTransactionsList(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControllerApi.controllerTransactionsList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ControllerApi - factory interface
 */
export const ControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ControllerApiFp(configuration)
    return {
        /**
         *
         * @summary Activate telegram bot
         * @param {string} botId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerBotActivate(botId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.controllerBotActivate(botId, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Register telegram bot on platform
         * @param {BotCreateRequest} botCreateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerBotCreate(botCreateRequest: BotCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<Bot> {
            return localVarFp.controllerBotCreate(botCreateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Deactivate telegram bot
         * @param {string} botId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerBotDeactivate(botId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.controllerBotDeactivate(botId, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Delete telegram bot from platform
         * @param {string} botId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerBotDelete(botId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.controllerBotDelete(botId, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Get telegram bot on platform
         * @param {string} botId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerBotGet(botId: string, options?: RawAxiosRequestConfig): AxiosPromise<Bot> {
            return localVarFp.controllerBotGet(botId, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary List all telegram bots on platform
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerBotList(options?: RawAxiosRequestConfig): AxiosPromise<Array<BotListResponseBotsInner>> {
            return localVarFp.controllerBotList(options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Update telegram bot on platform
         * @param {string} botId
         * @param {BotUpdateRequest} botUpdateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerBotUpdate(botId: string, botUpdateRequest: BotUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<Bot> {
            return localVarFp.controllerBotUpdate(botId, botUpdateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Create product for telegram bot
         * @param {ProductCreateRequest} productCreateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerProductCreate(productCreateRequest: ProductCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<Product> {
            return localVarFp.controllerProductCreate(productCreateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Delete product for telegram bot
         * @param {string} productId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerProductDelete(productId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.controllerProductDelete(productId, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Get product for telegram bot
         * @param {string} productId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerProductGet(productId: string, options?: RawAxiosRequestConfig): AxiosPromise<Product> {
            return localVarFp.controllerProductGet(productId, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary List all products for telegram bot
         * @param {string} botId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerProductList(botId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<ProductListResponseProductsInner>> {
            return localVarFp.controllerProductList(botId, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Update product for telegram bot
         * @param {string} productId
         * @param {ProductUpdateRequest} productUpdateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerProductUpdate(productId: string, productUpdateRequest: ProductUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<Product> {
            return localVarFp.controllerProductUpdate(productId, productUpdateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary List of promt presets for telegram bot
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerPromptPresetList(options?: RawAxiosRequestConfig): AxiosPromise<Array<PromptPresetListResponsePromptPresetsInner>> {
            return localVarFp.controllerPromptPresetList(options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Get statistics for user
         * @param {string} botId
         * @param {string} startTime
         * @param {string} endTime
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerStatisticsGet(botId: string, startTime: string, endTime: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<StatisticsGetResponseRecordsInner>> {
            return localVarFp.controllerStatisticsGet(botId, startTime, endTime, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Deposit transaction
         * @param {TransactionBillRequest} transactionBillRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerTransactionBill(transactionBillRequest: TransactionBillRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.controllerTransactionBill(transactionBillRequest, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Get transactions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controllerTransactionsList(options?: RawAxiosRequestConfig): AxiosPromise<Array<TransactionsListResponseTransactionsInner>> {
            return localVarFp.controllerTransactionsList(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ControllerApi - interface
 */
export interface ControllerApiInterface {
    /**
     *
     * @summary Activate telegram bot
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotActivate(botId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     *
     * @summary Register telegram bot on platform
     * @param {BotCreateRequest} botCreateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotCreate(botCreateRequest: BotCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<Bot>;

    /**
     *
     * @summary Deactivate telegram bot
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotDeactivate(botId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     *
     * @summary Delete telegram bot from platform
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotDelete(botId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     *
     * @summary Get telegram bot on platform
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotGet(botId: string, options?: RawAxiosRequestConfig): AxiosPromise<Bot>;

    /**
     *
     * @summary List all telegram bots on platform
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotList(options?: RawAxiosRequestConfig): AxiosPromise<Array<BotListResponseBotsInner>>;

    /**
     *
     * @summary Update telegram bot on platform
     * @param {string} botId
     * @param {BotUpdateRequest} botUpdateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerBotUpdate(botId: string, botUpdateRequest: BotUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<Bot>;

    /**
     *
     * @summary Create product for telegram bot
     * @param {ProductCreateRequest} productCreateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductCreate(productCreateRequest: ProductCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<Product>;

    /**
     *
     * @summary Delete product for telegram bot
     * @param {string} productId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductDelete(productId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     *
     * @summary Get product for telegram bot
     * @param {string} productId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductGet(productId: string, options?: RawAxiosRequestConfig): AxiosPromise<Product>;

    /**
     *
     * @summary List all products for telegram bot
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductList(botId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<ProductListResponseProductsInner>>;

    /**
     *
     * @summary Update product for telegram bot
     * @param {string} productId
     * @param {ProductUpdateRequest} productUpdateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerProductUpdate(productId: string, productUpdateRequest: ProductUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<Product>;

    /**
     *
     * @summary List of promt presets for telegram bot
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerPromptPresetList(options?: RawAxiosRequestConfig): AxiosPromise<Array<PromptPresetListResponsePromptPresetsInner>>;

    /**
     *
     * @summary Get statistics for user
     * @param {string} botId
     * @param {string} startTime
     * @param {string} endTime
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerStatisticsGet(botId: string, startTime: string, endTime: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<StatisticsGetResponseRecordsInner>>;

    /**
     *
     * @summary Deposit transaction
     * @param {TransactionBillRequest} transactionBillRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerTransactionBill(transactionBillRequest: TransactionBillRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     *
     * @summary Get transactions
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    controllerTransactionsList(options?: RawAxiosRequestConfig): AxiosPromise<Array<TransactionsListResponseTransactionsInner>>;

}

/**
 * ControllerApi - object-oriented interface
 */
export class ControllerApi extends BaseAPI implements ControllerApiInterface {
    /**
     *
     * @summary Activate telegram bot
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public controllerBotActivate(botId: string, options?: RawAxiosRequestConfig) {
        return ControllerApiFp(this.configuration).controllerBotActivate(botId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Register telegram bot on platform
     * @param {BotCreateRequest} botCreateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public controllerBotCreate(botCreateRequest: BotCreateRequest, options?: RawAxiosRequestConfig) {
        return ControllerApiFp(this.configuration).controllerBotCreate(botCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Deactivate telegram bot
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public controllerBotDeactivate(botId: string, options?: RawAxiosRequestConfig) {
        return ControllerApiFp(this.configuration).controllerBotDeactivate(botId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Delete telegram bot from platform
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public controllerBotDelete(botId: string, options?: RawAxiosRequestConfig) {
        return ControllerApiFp(this.configuration).controllerBotDelete(botId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Get telegram bot on platform
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public controllerBotGet(botId: string, options?: RawAxiosRequestConfig) {
        return ControllerApiFp(this.configuration).controllerBotGet(botId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary List all telegram bots on platform
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public controllerBotList(options?: RawAxiosRequestConfig) {
        return ControllerApiFp(this.configuration).controllerBotList(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Update telegram bot on platform
     * @param {string} botId
     * @param {BotUpdateRequest} botUpdateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public controllerBotUpdate(botId: string, botUpdateRequest: BotUpdateRequest, options?: RawAxiosRequestConfig) {
        return ControllerApiFp(this.configuration).controllerBotUpdate(botId, botUpdateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Create product for telegram bot
     * @param {ProductCreateRequest} productCreateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public controllerProductCreate(productCreateRequest: ProductCreateRequest, options?: RawAxiosRequestConfig) {
        return ControllerApiFp(this.configuration).controllerProductCreate(productCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Delete product for telegram bot
     * @param {string} productId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public controllerProductDelete(productId: string, options?: RawAxiosRequestConfig) {
        return ControllerApiFp(this.configuration).controllerProductDelete(productId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Get product for telegram bot
     * @param {string} productId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public controllerProductGet(productId: string, options?: RawAxiosRequestConfig) {
        return ControllerApiFp(this.configuration).controllerProductGet(productId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary List all products for telegram bot
     * @param {string} botId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public controllerProductList(botId: string, options?: RawAxiosRequestConfig) {
        return ControllerApiFp(this.configuration).controllerProductList(botId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Update product for telegram bot
     * @param {string} productId
     * @param {ProductUpdateRequest} productUpdateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public controllerProductUpdate(productId: string, productUpdateRequest: ProductUpdateRequest, options?: RawAxiosRequestConfig) {
        return ControllerApiFp(this.configuration).controllerProductUpdate(productId, productUpdateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary List of promt presets for telegram bot
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public controllerPromptPresetList(options?: RawAxiosRequestConfig) {
        return ControllerApiFp(this.configuration).controllerPromptPresetList(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Get statistics for user
     * @param {string} botId
     * @param {string} startTime
     * @param {string} endTime
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public controllerStatisticsGet(botId: string, startTime: string, endTime: string, options?: RawAxiosRequestConfig) {
        return ControllerApiFp(this.configuration).controllerStatisticsGet(botId, startTime, endTime, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Deposit transaction
     * @param {TransactionBillRequest} transactionBillRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public controllerTransactionBill(transactionBillRequest: TransactionBillRequest, options?: RawAxiosRequestConfig) {
        return ControllerApiFp(this.configuration).controllerTransactionBill(transactionBillRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Get transactions
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public controllerTransactionsList(options?: RawAxiosRequestConfig) {
        return ControllerApiFp(this.configuration).controllerTransactionsList(options).then((request) => request(this.axios, this.basePath));
    }
}
